README.md
Hi,
I've just found an issue about _.find.
Thanks for your contribution !!
Best
=> Fixes native support for _.find

README.md
Makes underscore look shorter. This PR fixes it by not assigning either.
=> The comparison here isn't fair

README.md
=> add assign

README.md
ESCMAScript2015 -> ECMAScript2015. 😄
=> A really tiny typo in the first paragraph of README.md

README.md
I found the ordering of the methods a bit arbitrary, and thought it would get ever more unwieldy if/when more methods are added. I alphabetised the methods under headings that match the LD/_ documentation (and added a caveat in the 'Collection' section regarding the fact all native methods are specifically for arrays). Sorry about the long PR, but it's literally just moving the methods around + adding some headers.
---
---
=> Document Structure

.gitignore, .travis.yml, README.md
Because package.json says >=4.0
Remove unneeded file
Minor whitespace fix
=> remove iojs and add node6

README.md
Replace fancy character with plain comment text
=> Code consistency fix

lib/rules/all.js, package.json, tests/lib/rules/all.js
=> use camelCase

README.md
=> Update Browser-Logo Links

README.md, configuring.md, index.js, lib/rules/all.js, lib/rules/rules.json, tests/index.js, tests/lib/rules/all.js
I have changed safe to compatible
Remove the config strict. By default it's strict. If you need warn you need to specify it.
Closes #53
Closes #54
=> Adds some default ESLint configs

README.md
Add alternative to `_.without` closes #33
=> Alternative for _.without

README.md, lib/rules/rules.json, tests/lib/rules/all.js
Add altanative `_.values` to `Object.values` 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values
=> Add _.values / Object.values

README.md, lib/rules/rules.json, tests/lib/rules/all.js
Append altanative `toPairs` to `Object.entries`
=> Add  _.toPairs / _.entires / _.pairs

README.md
=> fixed checkmark

README.md
Append compact altanative function
=> Add alternative _.compact

README.md
=> Fix README order

README.md
Append alternative `_.head` and `_,tail` with destructuring and spread operator
=> Add alternative head and tail

README.md
Append alternative range with `Array.from` and `Array.keys`
=> Append alternative range 

README.md
[].filter() returns will auto use truth rules.Just like !!.
=> [].filter() returns will auto use truth rules.Just like !!.

README.md
Append altanative function for `flatten` and `flattenDeep`
=> Append flatten and flattenDeep

.travis.yml, lib/rules/rules.json, tests/index.js
the second parameter could be an object (The `_.matches` iteratee shorthand)
=> find and findIndex should not be compatible

README.md, lib/rules/rules.json, tests/lib/rules/all.js
This technique takes advantage of the new Set construct introduced in ES6 to ensure that no duplicates
are present in the resulting array.
=> Adding native _.uniq method replacement

README.md
=> Add _.groupBy equivalent

.travis.yml, package.json, tests/index.js, tests/unit/all.js
Example code has mistake sometime.
I think code snippet example maybe need testing.
Test code and structure is draft ( only `compact, concat, fill`) .
=> Test for code-snippet

README.md
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
for compatibility.
=> added replacement for _.uniq

README.md
I added a fromPairs implementation based on reduce I used in one of my projects.
=> Added fromPairs implementation

README.md, tests/unit/all.js
I try to create chunk alternative.
=> Alternative chunk

.gitignore, README.md, tests/unit/all.js
Added native `pick` and `pickBy`
=> Added pick and pickBy

README.md, tests/unit/all.js
Closes https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/117
=> Add times function

README.md
=> Add isNil and isNull

README.md
_.times add:
` var result = [...Array(10).keys()]`
=> Update README.md _.times implement 

README.md, lib/rules/rules.json, tests/lib/rules/all.js
- needs pr for edge tp be merged before
=> startswith

README.md, tests/unit/all.js
I'm observed the issue [#166] and the _.inRange function is not exists into this repo.
I created a equivalent function and upgrade the README.md.
Thanks.
=> Add ._inRange equivalent.

README.md, lib/rules/rules.json, tests/lib/rules/all.js, tests/unit/all.js
=> added padStart and padEnd

lib/rules/rules.json, tests/lib/rules/all.js
=> Add _.isNil rule

README.md, tests/unit/all.js
Fix issue #204 
1) default value must be undefined, not null
2) Object.hasOwnProperty throws an exception, when it gets null or undefined
3) assert.equal think that null = undefined, changed to strictEqual
4) add some tests
=> Fix get throws error

README.md
This PR hopefully satisfies #145 
Added native examples for flatten and flattenDeep using flatMap. Also included the browser support section for flatMap
=> Added flatten/flattenDeep update using flatMap

README.md, lib/rules/rules.json, tests/lib/rules/all.js, tests/unit/all.js
- Added in `_.endsWith` to `README.md` and added tests for both `endsWith` and `startsWith`
=> add _.endsWith and add tests for both endsWith and startsWith

README.md
=> fix README endswith typo

README.md
We are having a spectrum channel. 😄
=> (chore):Add in spectrum chat link

lib/rules/all.js, tests/lib/rules/all.js
=> Add lodash-es support

README.md, tests/unit/all.js
- Adding lodash `_.clamp` function native replacement to `README.md`
=> add _.clamp to README.md

README.md
add new method to achieve _.fromPairs
=> add _.fromPairs new method

README.md
This defaults to undefined
lodash docs: https://lodash.com/docs/4.17.15#get
=> Make defaultValue for get optional

README.md
Lodash has a method called pull _.pull(array,[value]) that removes values from an array using strict equality for comparisons. The native solution uses a filter.
=> implement lodash pull

README.md
=> include slice as substitute for _initial

README.md
Relates to issue https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/271
=> added _.reject

README.md, lib/rules/rules.json
- Removed some copy-paste left-overs from _.endsWith
- Added changes from #285
- Added eslint rule
=> fix: remove copy-pasted content for _.isString

README.md, lib/rules/rules.json, tests/unit/all.js
Added native alternative for isFunction.
Duplicate of #259
=> feat: add isFunction

README.md, lib/rules/rules.json
Lodash has a castArray function which packages values into an array which is useful for taking in an array or a single argument. The solution is pretty trivial, but I think it's worth showing nonetheless.
=> Add _.castArray

README.md
Pass arguments to throttle function
=> Pass arguments to throttle function

README.md
Description is from lodash docs.
=> chore: update description of isFinite in README

README.md, tests/lib/rules/all.js, tests/unit/all.js
* Fix some typo: native~~h~~Array, ~~reduntant~~, ~~falsey~~
* Add missing parentheses
=> Fix typos and syntax errors

README.md
see https://lodash.com/docs#map
see https://caniuse.com/mdn-javascript_operators_destructuring
see https://caniuse.com/object-entries
=> Add polyfill for _.map(Collection)

README.md, lib/rules/rules.json, tests/unit/all.js
Add native alternative for `capitalize`
=> Add _.capitalize

README.md, lib/rules/rules.json, tests/unit/all.js
Add native alternative for `unionBy`
=> Add _.unionBy

README.md, lib/rules/rules.json, tests/unit/all.js
This was a simple one, figured I'd add it either way.
=> Add rule for _.defaults

README.md, tests/unit/all.js
README contains `_.upperFirst`, but no `_.lowerFirst`.
=> Add _.lowerFirst

README.md, tests/unit/all.js
Add native alternative for _.last
=> Add Array.at(-1) which equals to _.last

README.md
Hey,
Just in case my recently opened issue is actually an issue #344, here's the MR.
Happy if you close it if I'm wrong.
=> update collectionKeyBy so it works for objects

README.md
I've gone through all lines and _told_ spaces to behave!
Preview: https://github.com/szepeviktor/You-Dont-Need-Lodash-Underscore/tree/patch-1
=> Improve README even more

README.md, lib/rules/rules.json
Closes https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/349
=> Add _.cloneDeep
