README.md

You have a section called `_.contains` but you never actually use it, you use the alias. So just name the section the alias, and actually refer to it's alternate version `_.contains`, much easier to understand and keep track of

Use _.includes and call it _.includes

---

README.md

Try to improve https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/issues/34
I wrote a simple script to do the transform(using [standard-format](https://github.com/maxogden/standard-format)), and tried to keep my footprint as small as possible with some tricks.
```js
var fs = require('fs')
var format = require('standard-format').transform
var content = fs.readFileSync('./README.md', {encoding: 'utf-8'})
var re = /\ *```js\n([^`]*)```/g
var m = re.exec(content)
while (m) {
content = content.replace(m[1],
format(m[1])
.split('\n')
.map(function (line) { return line ? ('  ' + line.replace(/^;/, '')) : '' })
.join('\n') + '  '
)
m = re.exec(content)
}
fs.writeFile('./README.md', content, {encoding: 'utf-8'})
```
This transform mainly removed all unnecessary semicolons and adjust the …

format code by JavaScript Standard Style #34

---

README.md

More for completeness than anything else, given the lodash version just wraps native for chaining purposes anyway.

Added `_.concat`/`Array.prototype.concat`

---

README.md

Well, turns out markdown makes it harder to format the citations on blockquotes and seperate the individual quotes than I'd thought. The markdown comes out a little messy, so not sure if this is needed; if anyone has a simpler method, I'm all ears.

Quotes formatting

---

.gitignore
README.md
index.js
lib/rules/all.js
package.json
tests/lib/rules/all.js

Thanks for putting this repository together and congrats on making [Github Trending](https://twitter.com/trendinggithub/status/748876878279274496)! (That's how I found out about it.)
This PR turns the repository into an ESLint plugin. If you're using ESLint (you should be!) you can add this plugin to identify places in your codebase where you don't (may not) need Lodash / Underscore.
Example output:
```sh
$ grunt eslint
Running "eslint:target" (eslint) task
/code/some-project/src/account/account-details/account-header-controller.controller.js
27:16  error  Consider using the native Array.some()  you-dont-need-lodash-underscore/all
/code/some-project/src/account/activity/activity-order-list.controller.js
33:7   error  Consider using the native Array.forEach() …
```

Turns the repository into an ESLint plugin!

---

lib/rules/all.js
tests/lib/rules/all.js

`callee.object` doesn't always exist nor does `callee.property` even in the context of Underscore/Lo-Dash (see chaining: https://lodash.com/docs#_)
Unrelated, but the `"isNaN"` rule kebab-cases to `is-na-n`, so perhaps it would be better to rename it to `"isNan"` in the JSON file.

Fixed crashes

---

README.md

Suppor for `indexOf` determined from here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf
:no_entry_sign: This **will not** work with complex objects like this:
```js
var array = [{a:"foo", b:true},{a:"foo", b:false},{a:"bar", b:true}, {a:"bar", b:false}]
array.indexOf({a:"bar", b:true}) > -1
//always returns false
```
So it does include a note about this caveat.

Add another _.includes alternative

---

README.md

Since underscore's `_.pluck` method was just a shortcut for a feature of `_.map`, this can also be replaced in the same way.
Slightly related, I've put all of these into a configuration file for TSLint: https://gist.github.com/chrismbarr/937a7324cca3ee2f6bfed4ae553afe8f

Providing alternative to _.pluck()

---

README.md

_.pluck was removed since lodash v4.00. Since _.map(https://lodash.com/docs/4.17.0#map) provided the same function, we should just use _.map in example.

remove pluck

---

README.md

Without a blank line after raw HTML, the subsequent markdown doesn't get rendered as intended.

README.md: Fix markdown immediately following raw HTML

---

README.md

I think "Browser support" seems is child element of each functions.

Fix browser support block's indent

---

README.md

Fixed the error of the function name.This error causes the function to not execute correctly.

fix example for  _.template

---

README.md

While using this repo as a guideline for replacing some stuff, I noticed that the `flatten` implementation is wrong. If I try to execute I receive this error:
I think that this fixes it.
Fix #100

Fix flatten implementation

---

lib/rules/all.js
tests/lib/rules/all.js

This is a partial fix for #98 in that it will detect `"lodash/map"` ImportDeclarations.

Add import declaration support

---

README.md

This is resilient to situations where the input array is not an actual array (like lodash)

Alternative way for _first/_last

---

README.md

Hi all,
The first is unneccessary because the iteration result `a` is already flatten.
Thanks.

update(flattenDeep): remove an redundant call of flattenDeep

---

README.md

I've played with these alternatives a bit and am fairly confident they replace the Underscore/Lodash versions.
I **did not** test this on all browsers. I did copy the compatibility chart from `without` thinking they would be about the same.
I don't think this would have any eslint rules as `without` has none.

Add intersection and difference examples

---

README.md

`Array.from` will only work if you pass `{length: 10}` as first argument instead of just `10`see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Description for more info

update times example to use correct parameter

---

README.md

Three missing examples have been added for _.range replacement using `keys()` solution.
Also ES implements signed zeros thus in this case `0` multiplied by `-1` is equal to `-0` but usually that didn't matter since `+0 === -0` is equal to `true`.
If it's a meaningful problem you can always use `parseInt()` in map which converts `-0` to `+0` and leave rest of integers untouched.

Add missing examples and fix incorrect output in _.range

---

README.md

In Lodash/Underscore `_.sortBy` and `_.orderBy` both return copies of the array. The native `sort` modifies the array in place; something that can be very unexpected if you're not familiar with the native sort. A simple `.concat()` restores the expected behavior.
I couldn't find any relevant tests to modify, so I think this is a documentation only change. If I missed something, please let me know!

Updated native sort example to better match Lodash

---

README.md

I have also renamed `paths` to `keys` and `path` to `key` to make variables sounds more intuitive.

Utilize reduce in Native _.pick implementation

---

README.md
tests/unit/all.js

Added `_.extend` (including the unit tests) and a functional way of doing
it.
Added the missing unit tests for `_.assign` as well.
fix #119

Added _.extend

---

README.md

Fixes _.get snippet example since it can't really handle the `a[0].b.c` syntax

Updates _.get snippet

---

README.md

I found `flatten` and `flattenDeep` can replace with `flat()` function.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
It's so edge function, and I not remove `reduce` version.

Append ES2019 flat() version

---

configuring.md
index.js

On line 45 of [./configuring.md](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/edit/master/configuring.md) it says....
```js
"extends" : ["plugin:you-dont-need-lodash-underscore/compatible-error"],
```
However `compatible-error` isn't set up. I think it should be because that will prevent silly inclusions in a project but not show all the warnings which you'd get with plain `"plugin:you-dont-need-lodash-underscore/compatible"`.
This PR enables `compatible-error`
Thanks, great project!

feat: enable compatible-error

---

lib/rules/all.js
tests/lib/rules/all.js

```js
import { keys } from 'lodash';
```
Should now be detected for example.
Tests were updated.

Fixes #98: Adding support for named imports

---

lib/rules/all.js
tests/lib/rules/all.js

Adds support for the following examples:
```js
const { indexOf } = require('lodash');
const { indexOf: x } = require('lodash');
({ indexOf } = require('lodash'));
({ indexOf: x } = require('lodash'));
const indexOf = require('lodash.indexof');
const indexOf = require('lodash/indexOf');
```
Also fixes a small issue introduced at https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/195 with the `import` detection:
```js
import { indexOf as x } from 'lodash'; // would not be detected
```

Fixes #98: Adding support for notifying on `require("lodash")`

---

README.md

Choosing a side between `key in object` and `object.hasOwnProperty` was hard, so I picked the most explicit one :)

Avoid ignoring false-like values ('', 0, false, ...) for _.pick

---

README.md

Far shorter (and for me easier to understand) Syntax for inRange.
I'm not sure how support for defaults is, as I usually use TypeScript which Polyfills these, but you may just want to get rid of the old syntax.

 Shorter alternative syntax for inRange and add actual native representation of partial

---

README.md
tests/unit/all.js

I created this PR to correct the `._split` test's. Atually, the comparison used is based from returned Array, then, was necessary add the `JSON.stringify` function to help into test execution.

Fix broken Unit Test's

---

README.md

`array` should have been `arrays` and there was an extra `)`. Thank you for putting together this very useful list!

Fixed syntax error

---

README.md
lib/rules/rules.json
tests/lib/rules/all.js
tests/unit/all.js

add in for:  https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/201

(feature)Add in Number.IsInteger

---

tests/lib/rules/all.js

Removed this. It sometimes caused merge conflicts which caused extra unnecessary rebase burden.

(chore)remove rule count, as it often caused merge conflicts

---

README.md
tests/unit/all.js

Fix random()

---

README.md
lib/rules/rules.json

This PR adds native JS alternative for Lodash `_.dropRight`.
In my current project, we are extensively using`Lodash`.
Realized It's adding more weight to the app, I started to implement the `lodash` functionalities with native JavaScript.
Found this library that has a collection of most alternatives.
Thank you so much for this wonderful collection.
And, I would love to contribute.
Please let me know the contribution guidelines and process.
I will add the missed ones whenever I get time.

Add _.dropRight native implementation

---

lib/rules/all.js
tests/unit/all.js

I believed I was able to fix it. While I was doing console.log's I realized that the callee objects for the two different lines (_(myVar).isUndefined() v.s. _.isUndefined(myVar)) didn't match. The former had a structure such that:
callee.object.callee.name = '_'
rather than,
callee.object.name = '_'
This means that in certain odd cases, you'll have to go one level deeper into the callee object to find the name you are looking for. I've changed the assigning of objectName accordingly.
Fixed #208

Fixing error for OOP isUndefined.

---

lib/rules/all.js
tests/lib/rules/all.js

The changes made to line 28 of ./lib/rules/all.js in Pull Request #219 resulted in a TypeError when trying to lint cases where you have the evaluation of nested functions, i.e.
`myNestedFunction(2)(2)`
where myNestedFunction(2) had returned a function, which you then evaluate with an argument of 2. This was due to a hole in the logic of the new statement which is fixed in this new Pull Request.
`const objectName = callee.name || (callee.object && callee.object.name) || (callee.object.callee && callee.object.callee.name);`
is now
`const objectName = callee.name || (callee.object && callee.object.name) || (callee.object && callee.object.callee && callee.object.callee.name);`
And that is because in the first version, you have the first two statements evaluate as false, and then it goes to …

Fixing TypeError For Nested Function Evaluations and Adding New Tests

---

README.md

As mentioned in Issue #110, _.reverse was incorrectly labeled as Lodash only in README.md despite having a listed Native equivalent. This has been removed.
In #164, it was mentioned that there was no mention of null safety in any of the rules or README. It was agreed upon in the comments of that Issue that a warning about null safety was sufficient. I have added this to README.md.
This fixes Issue #110 and Issue #164.

Correcting README file for Issues #110 and #164

---

lib/rules/rules.json
tests/lib/rules/all.js
tests/unit/all.js

Added rules for _.flatten() in lib/rules/rules.json, using the .reduce() method as the suggestion given that it is the most widely compatible.
I've also included linter tests in tests/lib/rules/all.js for _.flatten() along with .reduce(), .flat, and .flatMap() as the valid alternatives.
Finally, I've included unit tests in tests/unit/all.js to verify that .reduce() and _.flatten() produce the same results for a two-layer and multi-layer array. 
Currently passes all linter and unit tests using Mocha.
This was done in response to Issue #145.

Adding rules and tests for _.flatten()

---

README.md
lib/rules/rules.json
tests/lib/rules/all.js
tests/unit/all.js

As suggested in #125, I have included Object.entries.forEach() as a secondary suggestion in the rules. This is important given that, as it is, object inputs with _.forEach() will result in getting a suggestion from Eslint that is incorrect (as mentioned in #229).
I have included the object alternative in the suggestion statement in the rules, and I have created rule and unit tests for _.forEach for both array and object versions. Currently, all tests pass.
Finally, I have updated the README file to include the secondary suggestion and have included the compatibility for Object.entries().forEach() based on the compatibility listed for Object.entries() on MDN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries).
A more rigorous solution would be …

Adding Object.entries().forEach() as alternative for _.each() and _.forEach()

---

README.md

As I have added an object alternative to _.each() in #231, the warning about the Collections methods in the table of contents and the Collections section being array-only methods was no longer accurate and thus could be confusing to users reading through the documentation.
I have changed those two warnings to read that they are "mostly" all array methods, and that if no object methods are listed, then you still may need Lodash/Underscore.
I apologize for not updating this in the mentioned PR.

Updating README file to be consistent with #231

---

README.md
tests/unit/all.js

Make get to support keys with dots. For example:
```
get({ 'a.b': 4, a: { b: 5 } }, 'a.b') // => 4
get({ 'a.a': { b: [ { 'c.c': 4 }, 2, 5 ] } }, ['a.a', 'b', 0, 'c.c']) // => 4
```
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/242

Allow get to support keys with dots

---

README.md

- Update README to make it clear that the Native method does not support
`Set` or `Map`.

Correcting README for issue #256

---

README.md
tests/unit/all.js

During the process of dropping lodash for [hexo](https://github.com/hexojs/hexo) project, we have faced serious obstacles when replacing `lodash.assignIn` with native javascript. We have tried the example function from the README but soon run into serious performance regression. After some investigations, it turns out that the `Object.getPrototypeOf()` is the culprit.
After trying `Object.getPrototypeOf()`, `Reflect.getPrototypeOf()` even the deprecated `__proto__`, the performance regression remains. We finally drops `lodash.assignIn` (https://github.com/hexojs/hexo/pull/3969) with a pure javascript alternative without bringing in any performance regression. It proves that `for...in...` is still the fastest way to iterate over the properties of an object.

New faster _.extend alternative

---

README.md
lib/rules/rules.json

What I've done:
- In the README.md I replaced the ES6 object destructing example with ES11 [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
- In the rules.json I added a new rule for _.get suggesting to use optional chaining and nullish coalescing operator instead

add optional chaining for _.get in README.md and add eslint rule (#147)

---

.travis.yml
tests/unit/all.js

- Unit tests errors are no longer ignored in Travis builds
- Removes EOL Node.js versions and adds 14 to the matrix

chore: enable travis failures

---

README.md

The versions of first() and last() with 2 parameters are only in Underscore, not in Lodash.

Comment a couple of calls as being in Underscore

---

docs/README.md
docs/index.html

Hi there
Actually I never used your eslint plugin.  
Instead, I came looking up things in your repos readme allot, since that rendered as a great quick documentation for me.
The only flaw so far was that the readme isn't all that great to navigate.
I reckon with [Docsify](https://github.com/docsifyjs/docsify/) the exact same Readme can be rendered into a nicer to use webpage with next to no effort at all for you guys
It doesn't even require a build.
All you'd need to change would be enabling github pages for the docs directory of your project and https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore would be ready.
See: https://casaper.github.io/You-Dont-Need-Lodash-Underscore/#/

feat(gh-page): zero effort gh-page from readme with docsify

---

package.json

`package.json` specifies a `main` entry of `lib/index.js`, which doesn’t exist. A bit untidy, and Yarn Berry spits out tedious warnings about invalid entries.

chore: fix main entry in package.json

---

README.md

1. sort _.startsWIth example alphabetically following quick links
2. fix broken quick links

fix broken quick links and sort example order

---

README.md

A start for converting examples to typescript.
Starting to full fill my own created issue #309.

feat(typescript-examples): _.pull

---

README.md

Fix description that claims `_.isNull` to check for undefined. 
Calling `_.isNull(undefined)` returns `false`. The observed behaviour can also be verified from source https://github.com/lodash/lodash/blob/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/isNull.js#L17

Fix: errorneous description for _.isNull

---

README.md

The `david-dm.org` website is down for 3 months, and the project `alanshaw/david` is not actively maintained anymore. The `david-dm.org` should be considered dead, thus badges should be removed from README.

Docs: remove david-dm.org badge from README

---

tests/lib/rules/all.js

Looks like `arr[0]` was added like suggested in #312 but the test was not updated causing `yarn test` failure.

Fix _first test

---

README.md
lib/rules/rules.json
tests/lib/rules/all.js
tests/unit/all.js

- Add new rule for .head()
- Modify existing rules for .first() & .last()
Suggest the use of Array.prototype.at() instead for ES13(I would prefer to use Ecmascript 2022, but didn't see any previous use of that convention).

head, first & last rules

---

.github/workflows/pr.yml

v1.1.1 emitted warnings because of usage of Node.js v12.

Upgrade dependabot/fetch-metadata

---

README.md
tests/unit/all.js

add entry for isPlainObject

---

README.md

Removed unintended code from `isPlainObject`.
See comment https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/384#pullrequestreview-1726609882.

Correct isPlainObject()

---

README.md
tests/unit/all.js

This PR will fix #393 .
* shows explicitly the _.pick ignores non-existent key
* modify test implementation equavalent to README.md example

Fix #393 remove a destructuring assignment example on _.pick native implementation

---

README.md

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy
One thing to note - MDN says Safari uses a different function - `Array.prototype.groupToMap`. Not sure if it is worth mentioning.

Mention Object.groupBy()
